version: "3"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
      - JWT_SECRET=your_jwt_secret
  mongo:
    image: mongo
